import express from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from './middleware/rateLimiter.js';
import xss from 'xss-clean';
import hpp from 'hpp';
import dotenv from 'dotenv';
import './config/env.js';
import connectDatabase from './config/db.js';
import { logger, httpLogger } from './utils/logger.js';
import requestLogger from './middleware/requestLogger.js';
import sanitizeMiddleware from './middleware/sanitizeMiddleware.js';
import authRoutes from './routes/authRoutes.js';
import contactRoutes from './routes/contactRoutes.js';
import getStartedRoutes from './routes/getStartedRoutes.js';
import aiRoutes from './routes/aiRoutes.js';
import dashboardRoutes from './routes/dashboardRoutes.js';
import quoteRoutes from './routes/quoteRoutes.js';
import supportRoutes from './routes/supportRoutes.js';
import ApiResponse from './utils/apiResponse.js';
import errorMiddleware from './middleware/errorMiddleware.js';

dotenv.config();
const app = express();
connectDatabase().catch((error) => logger.error('Database startup check failed', { message: error.message }));
app.use(express.json({ limit: '10kb' }));
app.use(express.urlencoded({ extended: true, limit: '10kb' }));
app.use(cookieParser());
app.use(helmet());
app.use(xss());
app.use(hpp());
app.use(sanitizeMiddleware);
app.use(cors({ origin: process.env.CORS_ORIGIN?.split(',') || ['http://localhost:5176', 'http://localhost:3000', 'http://localhost:5174', 'http://localhost:4000'], credentials: true }));
app.use(requestLogger);
app.use(httpLogger);
app.use(rateLimit.general);
app.get('/health', (req, res) => ApiResponse.success(res, 'Server is running', { uptime: process.uptime(), database: 'supabase-postgresql' }));
app.get('/api', (req, res) => ApiResponse.success(res, 'API information', { version: 'v1', baseUrl: '/api/v1', endpoints: { auth: ['/api/v1/auth/register', '/api/v1/auth/login', '/api/v1/auth/logout', '/api/v1/auth/me'], contact: ['/api/v1/contact'], getStarted: ['/api/v1/get-started'], quote: ['/api/v1/quote'], support: ['/api/v1/support'], ai: ['/api/v1/ai/chat'], dashboard: ['/api/v1/admin/dashboard'] } }));
app.use('/api/v1/auth', rateLimit.auth, authRoutes);
app.use('/api/v1/contact', contactRoutes);
app.use('/api/v1/get-started', getStartedRoutes);
app.use('/api/v1/quote', quoteRoutes);
app.use('/api/v1/support', supportRoutes);
app.use('/api/v1/ai', rateLimit.ai, aiRoutes);
app.use('/api/v1/admin', dashboardRoutes);
app.use(errorMiddleware);
const PORT = parseInt(process.env.PORT, 10) || 4000;
app.listen(PORT, () => logger.info(`STONE TECH BACKEND is running in ${process.env.NODE_ENV || 'development'} mode on port ${PORT}`));
